# .github/workflows/claude_pr_review.yml
name: 'Claude Code PR Reviewer'

on:
  pull_request:
    types: [opened]

jobs:
  review:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Claude Code Review Action
        uses: anthropics/claude-code-action@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_AI_API_KEY }}
          prompt: |
            Act as an expert code reviewer.
            1. Provide a brief, high-level summary of the changes in this pull request.
            2. Review the code for potential security vulnerabilities ONLY.
            3. Post your findings as comments DIRECTLY on the relevant lines of code in the PR.
